apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: new-api-data
  namespace: new-api
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: auto-ebs-sc
  resources:
    requests:
      storage: 20Gi
